version: '3.8'

services:
  # Servicio para backend de FastAPI
  backend:
    build:
      context: ./backend
    container_name: backend_service
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=production
      - LOG_LEVEL=info
      - DATABASE_URL=postgresql://user:password@db:5432/app_db
    networks:
      - app_network

  # Servicio para frontend de Streamlit
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_service
    ports:
      - "8501:8501"
    depends_on:
      - backend
    networks:
      - app_network

  # Servicio para base de datos PostgreSQL
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_network      
      
  # Servicio para monitoreo con Grafana
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - app_network
      
  networks:
  app_network:
    driver: bridge