version: '3.8'

services:
  # Servicio para backend de FastAPI
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_service
    ports:
      - "8000:8000"
    networks:
      - app_network

  # Servicio para frontend de Streamlit
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_service
    ports:
      - "8501:8501"
    depends_on:
      - backend
    networks:
      - app_network

  # Servicio para base de datos PostgreSQL
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: #appml2024
      POSTGRES_DB: db-postgresql-appml
    ports:
      - "5432:5432"
    networks:
      - app_network      
      
  networks:
  app_network:
    driver: bridge