label_mapping = {
    0: "Paga al dia",
    1: "Cliente moroso"}

columns_train = [
    'atraso',
    'edad',
    'dias_lab',
    'exp_sf',
    'nivel_ahorro',
    'ingreso',
    'linea_sf',
    'deuda_sf',
    'score',
    'clasif_sbs',
    'zona_Amazonas',
    'zona_Ancash',
    'zona_Apurimac',
    'zona_Arequipa',
    'zona_Ayacucho',
    'zona_Cajamarca',
    'zona_Callao',
    'zona_Cuzco',
    'zona_Huancavelica',
    'zona_Huanuco',
    'zona_Ica',
    'zona_Junin',
    'zona_La Libertad',
    'zona_Lambayeque',
    'zona_Lima',
    'zona_Loreto',
    'zona_Madre de Dios',
    'zona_Moquegua',
    'zona_Pasco',
    'zona_Piura',
    'zona_Puno',
    'zona_San Martin',
    'zona_Tacna',
    'zona_Tumbes',
    'zona_Ucayali',
    'nivel_educ_SECUNDARIA',
    'nivel_educ_SIN EDUCACION',
    'nivel_educ_TECNICA',
    'nivel_educ_UNIVERSITARIA',
    'vivienda_ALQUILADA',
    'vivienda_FAMILIAR',
    'vivienda_PROPIA'
    ]